
# Permalinks
permalink: pretty

# Server config
source: ./docs
destination: ./_gh_pages
baseurl: /
host: 0.0.0.0
port: 9001
url: http://localhost:9001
encoding: UTF-8

# Custom config
current_version: 3.0.0
repo: https://github.com/IcaliaLabs/furatto

current_ip: 192.168.0.10
